
GET http://localhost:3000/api/student/profile


###

POST http://localhost:3000/api/auth/send-otp
content-type: application/json

{
    "email": "avenkatashiva@gmail.com"
}

###

POST http://localhost:3000/api/auth/verify-otp
content-type: application/json

{
    "email": "avenkatashiva@gmail.com",
    "otp": "177009"
}


###

POST http://localhost:3000/api/auth/verify-otp
content-type: application/json

{
    "email": "divyajanga55@gmail.com",
    "otp": "203439"
}

###

GET http://localhost:3000/api/auth/signout

###

POST http://localhost:3000/api/auth/signin
content-type: application/json

{
    "email": "divyajanga55@gmail.com",
    "password": "divya@55"
}

###

POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "email": "divyajanga55@gmail.com",
    "name": "Divya",
    "userType": "student",
    "password": "divya448",
    "id": "O170448"
}

###


POST http://localhost:3000/api/auth/update-profile
content-type: application/json

{
    "email": "divyajanga55@gmail.com",
    "mobile": "80234223234",
    "cls": "cse5",
    "year": "E4",
    "paName": "my father", 
    "paMobile": "82934234234", 
    "address" : "my adress"
}


###


POST http://localhost:3000/api/student/create-leave
content-type: application/json

{
    "name": "Buddi",
    "id":"O170448",
    "gender":"F",
    "year":"E4",
    "className": "T6",
    "dorm": "G20",
    "outpassType": "emergency",
    "reason": "Stomach pain",
    "caretaker": "caretaker-1@gmail.com",
    "warden": "warden-1@gmail.com",
    "date": "06-08-2011",
    "stuMobile": "9823889122",
    "prtMobile": "8123123923",
    "numDays": "1"
}


###

POST http://localhost:3000/api/auth/care-taker-login
content-type: application/json

{
    "email": "caretaker1@gmail.com",
    "password": "caretaker123"
}


###

POST http://localhost:3000/api/auth/warden-login
content-type: application/json

{
    "email": "warden1@gmail.com",
    "password": "warden123"
}

###

GET http://localhost:3000/api/student/get-leaves
content-type: application/json


###
